CREATE TABLE if not exists USERS
(
  ID           VARCHAR(32) NOT NULL,
  NAME          VARCHAR(32) NOT NULL,
  AGE          INT GENERATED ALWAYS AS (JSON_CONTENT ->> '$.age') VIRTUAL,
  JSON_CONTENT JSON        NOT NULL,
  CREATED_AT   VARCHAR(50) GENERATED ALWAYS AS (JSON_CONTENT ->> '$.createdAt') VIRTUAL,
  PRIMARY KEY (ID)
) CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;